export const PAKISTANI_CITIES = [
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Multan',
  'Hyderabad',
  'Islamabad',
  'Quetta',
  'Peshawar',
  'Sialkot',
  'Gujranwala',
  'Sukkur',
  'Larkana',
  'Shekhupura',
  'Rahim Yar Khan',
  'Jhang',
  'Dera Ghazi Khan',
  'Gujrat',
  'Sahiwal',
  'Wah Cantonment',
  'Mardan',
  'Kasur',
  'Okara',
  'Mingora',
  'Nawabshah',
  'Chiniot',
  'Kotri',
  'Kamoke',
  'Hafizabad',
  'Sadiqabad',
  'Mirpur Khas',
  'Burewala',
  'Jacobabad',
  'Kohat',
  'Khuzdar',
  'Dadu',
  'Khanewal',
  'Gojra',
  'Mandi Bahauddin',
  'Attock',
  'Bahawalnagar',
  'Phalia',
  'Tando Allahyar',
  'Ahmedpur East',
  'Vihari',
  'Jaranwala',
  'Kamalia',
  'Lodhran',
  'Swabi',
  'Wazirabad',
  'Dera Ismail Khan',
  'Charsadda',
  'Kandhkot',
  'Arifwala',
  'Turbat',
  'Nowshera',
  'Mianwali',
  'Bannu',
  'Bahawalpur',
  'Sargodha',
  'Abbottabad',
  'Jhelum',
  'Muzaffargarh',
  'Shikarpur',
  'Havelian',
  'Malakand',
  'Mansehra',
  'Zhob',
  'Gwadar',
  'Khairpur',
  'Bhakkar',
  'Badin',
  'Thatta',
  'Chitral',
  'Gilgit',
  'Skardu',
  'Muzaffarabad',
  'Mirpur (AJK)',
  'Rawalakot',
  'Kotli (AJK)',
  'Dina',
  'Pind Dadan Khan',
  'Sambrial',
  'Narowal',
  'Pasrur',
  'Shakargarh',
  'Zafarwal',
  'Daska',
  'Wazirabad',
  'Eminabad',
  'Qila Didar Singh',
  'Alipur Chatha',
  'Rasulnagar',
  'Sodhra',
  'Gakhar Mandi',
  'Ghakkhar',
  'Gujranwala Cantonment',
  'Kamoke Cantonment',
  'Muridke',
  'Ferozwala',
  'Shahdara Town',
  'Kot Abdul Malik',
  'Kala Shah Kaku',
  'Narowal',
  'Shakargarh',
  'Zafarwal',
  'Daska',
  'Pasrur',
  'Sambrial',
  'Dina',
  'Pind Dadan Khan',
  'Jhelum Cantonment',
  'Sargodha Cantonment',
  'Mianwali Cantonment',
  'Bannu Cantonment',
  'Kohat Cantonment',
  'Dera Ismail Khan Cantonment',
  'Peshawar Cantonment',
  'Mardan Cantonment',
  'Nowshera Cantonment',
  'Charsadda Cantonment',
  'Swabi Cantonment',
  'Attock Cantonment',
  'Wah Cantonment',
  'Taxila',
  'Hattar',
  'Haripur',
  'Ghazi',
  'Havelian Cantonment',
  'Abbottabad Cantonment',
  'Mansehra Cantonment',
  'Balakot',
  'Batagram',
  'Besham',
  'Chilas',
  'Dassu',
  'Gahkuch',
  'Gilgit Cantonment',
  'Gupis',
  'Ishkoman',
  'Juglot',
  'Khaplu',
  'Skardu Cantonment',
  'Shigar',
  'Sost',
  'Thall',
  'Yasin',
  'Astore',
  'Chilas Cantonment',
  'Gahkuch Cantonment',
  'Gupis Cantonment',
  'Ishkoman Cantonment',
  'Juglot Cantonment',
  'Khaplu Cantonment',
  'Shigar Cantonment',
  'Sost Cantonment',
  'Thall Cantonment',
  'Yasin Cantonment',
  'Astore Cantonment',
  'Chilas Cantonment',
  'Gahkuch Cantonment',
  'Gupis Cantonment',
  'Ishkoman Cantonment',
  'Juglot Cantonment',
  'Khaplu Cantonment',
  'Shigar Cantonment',
  'Sost Cantonment',
  'Thall Cantonment',
  'Yasin Cantonment',
  'Astore Cantonment',
  'Muzaffarabad Cantonment',
  'Mirpur Cantonment (AJK)',
  'Rawalakot Cantonment',
  'Kotli Cantonment (AJK)',
  'Bhambar',
  'Hattian Bala',
  'Jhelum Valley',
  'Neelum Valley',
  'Poonch',
  'Sudhanoti',
  'Bagh',
  'Haveli',
  'Kahuta',
  'Khunjerab',
  'Leepa Valley',
  'Naran',
  'Shogran',
  'Kaghan',
  'Ayubia',
  'Galiyat',
  'Malam Jabba',
  'Kalam',
  'Utror',
  'Gabral',
  'Bahrain',
  'Madyan',
  'Behrain',
  'Kalam Valley',
  'Mahodand Lake',
  'Saif-ul-Malook Lake',
  'Ansoo Lake',
  'Lulusar Lake',
  'Dudipatsar Lake',
  'Paye Meadows',
  'Shogran Meadows',
  'Siri Paye',
  'Nathia Gali',
  'Murree',
  'Patriata',
  'Bhurban',
  'Ayubia National Park',
  'Changla Gali',
  'Dunga Gali',
  'Khanspur',
  'Thandiani',
  'Sakesar',
  'Soon Valley',
  'Kallar Kahar',
  'Chakwal',
  'Talagang',
  'Bhaun',
  'Choa Saidanshah',
  'Dhudial',
  'Kotas',
  'Lawa',
  'Padshahan',
  'Sarai Alamgir',
  'Kharian',
  'Lalamusa',
  'Dingah',
  'Kunjah',
  'Mangla Cantt',
  'Sarai Alamgir Cantt',
  'Kharian Cantt',
  'Lalamusa Cantt',
  'Dingah Cantt',
  'Kunjah Cantt',
  'Mangla Cantt',
  'Gujrat Cantt',
  'Sialkot Cantt',
  'Daska Cantt',
  'Pasrur Cantt',
  'Sambrial Cantt',
  'Narowal Cantt',
  'Shakargarh Cantt',
  'Zafarwal Cantt',
  'Eminabad Cantt',
  'Qila Didar Singh Cantt',
  'Alipur Chatha Cantt',
  'Rasulnagar Cantt',
  'Sodhra Cantt',
  'Gakhar Mandi Cantt',
  'Ghakkhar Cantt',
  'Muridke Cantt',
  'Ferozwala Cantt',
  'Shahdara Town Cantt',
  'Kot Abdul Malik Cantt',
  'Kala Shah Kaku Cantt',
  'Taxila Cantt',
  'Hattar Cantt',
  'Haripur Cantt',
  'Ghazi Cantt',
  'Balakot Cantt',
  'Batagram Cantt',
  'Besham Cantt',
  'Dassu Cantt',
  'Astore Cantt',
  'Chilas Cantt',
  'Gahkuch Cantt',
  'Gupis Cantt',
  'Ishkoman Cantt',
  'Juglot Cantt',
  'Khaplu Cantt',
  'Shigar Cantt',
  'Sost Cantt',
  'Thall Cantt',
  'Yasin Cantt',
  'Bhambar Cantt',
  'Hattian Bala Cantt',
  'Jhelum Valley Cantt',
  'Neelum Valley Cantt',
  'Poonch Cantt',
  'Sudhanoti Cantt',
  'Bagh Cantt',
  'Haveli Cantt',
  'Kahuta Cantt',
  'Khunjerab Cantt',
  'Leepa Valley Cantt',
  'Naran Cantt',
  'Shogran Cantt',
  'Kaghan Cantt',
  'Ayubia Cantt',
  'Galiyat Cantt',
  'Malam Jabba Cantt',
  'Kalam Cantt',
  'Utror Cantt',
  'Gabral Cantt',
  'Bahrain Cantt',
  'Madyan Cantt',
  'Behrain Cantt',
  'Kalam Valley Cantt',
  'Mahodand Lake Cantt',
  'Saif-ul-Malook Lake Cantt',
  'Ansoo Lake Cantt',
  'Lulusar Lake Cantt',
  'Dudipatsar Lake Cantt',
  'Paye Meadows Cantt',
  'Shogran Meadows Cantt',
  'Siri Paye Cantt',
  'Nathia Gali Cantt',
  'Murree Cantt',
  'Patriata Cantt',
  'Bhurban Cantt',
  'Ayubia National Park Cantt',
  'Changla Gali Cantt',
  'Dunga Gali Cantt',
  'Khanspur Cantt',
  'Thandiani Cantt',
  'Sakesar Cantt',
  'Soon Valley Cantt',
  'Kallar Kahar Cantt',
  'Chakwal Cantt',
  'Talagang Cantt',
  'Bhaun Cantt',
  'Choa Saidanshah Cantt',
  'Dhudial Cantt',
  'Kotas Cantt',
  'Lawa Cantt',
  'Padshahan Cantt',
  'Sarai Alamgir Cantt',
  'Kharian Cantt',
  'Lalamusa Cantt',
  'Dingah Cantt',
  'Kunjah Cantt',
  'Mangla Cantt'
];
